name: Cypress CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Fazer checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Configurar Node.js compatível com Cypress 15.x
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.0' # compatível com Cypress 15.2.0

      # 3️⃣ Instalar dependências do projeto
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Limpar completamente o cache do Cypress (evita download corrompido)
      - name: Clear Cypress cache
        run: rm -rf ~/.cache/Cypress

      # 5️⃣ Instalar binário do Cypress com força
      - name: Install Cypress binary
        run: npx cypress install --force

      # 6️⃣ Rodar testes headless no Chrome
      - name: Run Cypress tests
        run: npx cypress run --headless --browser chrome

      # 7️⃣ Upload de vídeos/screenshots caso falhem testes
      - name: Upload artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots
