name: Cypress CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.0'  # Node compatível com Cypress 15.2.0

      - name: Install dependencies
        run: npm ci

      - name: Clear Cypress cache
        run: npx cypress cache clear

      - name: Run Cypress tests
        run: npx cypress run --headless --browser chrome

      - name: Upload artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots
