name: Cypress CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Node 22 para compatibilidade total
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # 🔹 Atualizado

      # 3️⃣ Instalar dependências
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Limpar cache do Cypress
      - name: Clear Cypress cache
        run: rm -rf ~/.cache/Cypress

      # 5️⃣ Instalar binário do Cypress
      - name: Install Cypress binary
        run: npx cypress install --force

      # 6️⃣ Rodar testes headless no Chrome
      - name: Run Cypress tests
        run: npx cypress run --headless --browser chrome

      # 7️⃣ Upload de artefatos em caso de falha
      - name: Upload artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots
